TARGET_COLOR_BGR = (0, 0, 255)
MEDIC_COLOR_BGR = (255, 0, 0)
ROBOT_COLOR_BGR = (0, 255, 0)

CAMERA_FOV = 30
DELAY_PER_ANGLE = .1
FIRE_DELAY = 0.6

TARGET_MODE_DEFAULT = False
MEDIC_MODE_DEFAULT = False
ROBOT_MODE_DEFAULT = False
PARALLEL_MODE = False

DISPLAY_MODE = False

FLYWHEEL_MODE_DEFAULT = True
FIRE_MODE_DEFAULT = True
AIM_MODE_DEFAULT = True

ARDUINO_CONNECTED = True
