TARGET_COLOR_BGR = (0, 0, 255)
MEDIC_COLOR_BGR = (255, 0, 0)
ROBOT_COLOR_BGR = (0, 255, 0)

CAMERA_FOV = 30
DELAY_PER_ANGLE = .2

TARGET_MODE_DEFAULT = True
MEDIC_MODE_DEFAULT = False
ROBOT_MODE_DEFAULT = True
PARALLEL_MODE = False

DISPLAY_MODE = True

FLYWHEEL_MODE_DEFAULT = False
FIRE_MODE_DEFAULT = False
AIM_MODE_DEFAULT = False

ARDUINO_CONNECTED = False;